
tasks:
  - init: |
      gcc -Wall -shared -fPIC -o ./libcmodule.so -I./test/c/ test/c/module.c
  - command: |
      sudo mv ./libcmodule.so /usr/lib/
      pip install -e .
      python test/test.py

vscode:
  extensions:
    - ms-python.python
    - llvm-vs-code-extensions.vscode-clangd
